"""baseline schema

Revision ID: 7a75b7caf589
Revises: 
Create Date: 2026-08-22 09:03:39.039710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a75b7caf589'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('reconstructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mesh_path', sa.String(length=512), nullable=True),
    sa.Column('mri_path', sa.String(length=512), nullable=True),
    sa.Column('ct_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('registration_confirmed', sa.Boolean(), nullable=True),
    sa.Column('export_status', sa.String(length=32), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('electrode_shafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reconstruction_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('electrode_type', sa.String(length=32), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('n_total_contacts', sa.Integer(), nullable=True),
    sa.Column('spacing_mm', sa.Float(), nullable=True),
    sa.Column('grid_rows', sa.Integer(), nullable=True),
    sa.Column('grid_cols', sa.Integer(), nullable=True),
    sa.Column('contact_diameter_mm', sa.Float(), nullable=True),
    sa.Column('contact_length_mm', sa.Float(), nullable=True),
    sa.Column('shaft_diameter_mm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['reconstruction_id'], ['reconstructions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seeg_recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reconstruction_id', sa.Integer(), nullable=True),
    sa.Column('task', sa.String(length=128), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reconstruction_id'], ['reconstructions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electrode_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shaft_id', sa.Integer(), nullable=True),
    sa.Column('contact_number', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('x_mm', sa.Float(), nullable=True),
    sa.Column('y_mm', sa.Float(), nullable=True),
    sa.Column('z_mm', sa.Float(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['shaft_id'], ['electrode_shafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('electrode_contacts')
    op.drop_table('seeg_recordings')
    op.drop_table('electrode_shafts')
    op.drop_table('reconstructions')
    op.drop_table('users')
    # ### end Alembic commands ###
